### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by davnov134** [jerrykingpku/Toolkit#1]
Hello,

right after running demo.m, there's an error:

Undefined function 'CountID' for input arguments of type 'double'.
Error in demo (line 24)
    CountID(iimg, imgNum, 100, 'Image:');

Seems like the CountID function is missing in the repo ...

**Comment by ivanDonadello** [comment]
I have the same problem, where can I find the CountId function?

**Comment by pengwangucla** [comment]
Sorry for late,  just updated. It is just a Counter function I wrote to simplify the counting of image.

**Comment by ivanDonadello** [comment]
Thank you very much!
