### ISSUE TITLE
missing CatVarargin function

### ISSUE THREAD

**Issue by ivanDonadello** [jerrykingpku/Toolkit#2]
Hello, I get the following error running the demo:

Undefined function 'CatVarargin' for input arguments of type 'struct'.

Error in region2box (line 4)
opt = CatVarargin(opt, varargin);

Error in GenPartMask>GetInstBox (line 65)
    instbox(iinst, :) = region2box(mask);

Error in GenPartMask (line 16)
    instbox = GetInstBox(inst_mask);

Error in demo (line 32)
    [partsMask, instbox, clsMask, instMask]  = GenPartMask(anno, anno.objects(1).mask, pimap,VOCPart.obj_id,
    mappings); 

It seems that the CatVarargin function/file is missing... Thank you very much for the attention.

**Comment by pengwangucla** [comment]
Hi Sorry for missing so many functions, I just updated those utilities to run the code

**Comment by ivanDonadello** [comment]
Now it works, thank you very much!
